### ISSUE TITLE
Questions about ASAN--

### ISSUE THREAD

**Issue by dhbbb** [junxzm1990/ASAN--#1]
Hello, ASAN-- team!
I noticed that the Fuzzing Test Cases you gave is about AFL. Can ASAN-- support libfuzzer or other fuzzers to test large-scale software?

**Comment by yzhang71** [comment]
> Hello, ASAN-- team! I noticed that the Fuzzing Test Cases you gave is about AFL. Can ASAN-- support libfuzzer or other fuzzers to test large-scale software?

Hi! This is a good question! Although we didn't test ASAN-- on libfuzzer, we believe you can apply ASAN-- on libfuzzer and other fuzzers, as long as you are using ASAN-- version Clang as compiler.

**Comment by dhbbb** [comment]
> > Hello, ASAN-- team! I noticed that the Fuzzing Test Cases you gave is about AFL. Can ASAN-- support libfuzzer or other fuzzers to test large-scale software?
> 
> Hi! This is a good question! Although we didn't test ASAN-- on libfuzzer, we believe you can apply ASAN-- on libfuzzer and other fuzzers, as long as you are using ASAN-- version Clang as compiler.

 Is ASAN-- version Clang means clang-4.0？

**Comment by dhbbb** [comment]
> > Hello, ASAN-- team! I noticed that the Fuzzing Test Cases you gave is about AFL. Can ASAN-- support libfuzzer or other fuzzers to test large-scale software?
> 
> Hi! This is a good question! Although we didn't test ASAN-- on libfuzzer, we believe you can apply ASAN-- on libfuzzer and other fuzzers, as long as you are using ASAN-- version Clang as compiler.

 Is ASAN-- version Clang means clang-4.0？

**Comment by yzhang71** [comment]
> > > Hello, ASAN-- team! I noticed that the Fuzzing Test Cases you gave is about AFL. Can ASAN-- support libfuzzer or other fuzzers to test large-scale software?
> > 
> > 
> > Hi! This is a good question! Although we didn't test ASAN-- on libfuzzer, we believe you can apply ASAN-- on libfuzzer and other fuzzers, as long as you are using ASAN-- version Clang as compiler.
> 
> Is ASAN-- version Clang means clang-4.0？

Yes, currently our stable version is Clang-4.0.0. We also migrated ASAN-- to LLVM-12.0.0, but it is preliminary version.

**Comment by dhbbb** [comment]
> > > > Hello, ASAN-- team! I noticed that the Fuzzing Test Cases you gave is about AFL. Can ASAN-- support libfuzzer or other fuzzers to test large-scale software?
> > > 
> > > 
> > > Hi! This is a good question! Although we didn't test ASAN-- on libfuzzer, we believe you can apply ASAN-- on libfuzzer and other fuzzers, as long as you are using ASAN-- version Clang as compiler.
> > 
> > 
> > Is ASAN-- version Clang means clang-4.0？
> 
> Yes, currently our stable version is Clang-4.0.0. We also migrated ASAN-- to LLVM-12.0.0, but it is preliminary version.
I try to apply ASan--to the OSS-fuzz project and I have run the following commands：
$ patch -p1 < patch_ASan--FuZZan
$ cd llvm-4.0.0-project
$ mkdir ASan--Build && cd ASan--Build
$ cmake -DLLVM_ENABLE_PROJECTS="clang;compiler-rt" -G "Unix Makefiles" ../llvm
$ make -j
Since libfuzzer has been integrated into clang, should I use “/home/llvm-4.0.0-project/ASan--Build/bin/clang 251” or "Clang-4.0.0."  to compile the target softwares?

**Comment by yzhang71** [comment]
> > > > > Hello, ASAN-- team! I noticed that the Fuzzing Test Cases you gave is about AFL. Can ASAN-- support libfuzzer or other fuzzers to test large-scale software?
> > > > 
> > > > 
> > > > Hi! This is a good question! Although we didn't test ASAN-- on libfuzzer, we believe you can apply ASAN-- on libfuzzer and other fuzzers, as long as you are using ASAN-- version Clang as compiler.
> > > 
> > > 
> > > Is ASAN-- version Clang means clang-4.0？
> > 
> > 
> > Yes, currently our stable version is Clang-4.0.0. We also migrated ASAN-- to LLVM-12.0.0, but it is preliminary version.
> > I try to apply ASan--to the OSS-fuzz project and I have run the following commands：
> > $ patch -p1 < patch_ASan--FuZZan
> > $ cd llvm-4.0.0-project
> > $ mkdir ASan--Build && cd ASan--Build
> > $ cmake -DLLVM_ENABLE_PROJECTS="clang;compiler-rt" -G "Unix Makefiles" ../llvm
> > $ make -j
> > Since libfuzzer has been integrated into clang, should I use “/home/llvm-4.0.0-project/ASan--Build/bin/clang 251” or "Clang-4.0.0."  to compile the target softwares?

Hi, for ASan--, you need to use "/home/llvm-4.0.0-project/ASan--Build/bin/clang" to compile fuzzing targets.

**Comment by blu3sh0rk** [comment]
> > > > > > Hello, ASAN-- team! I noticed that the Fuzzing Test Cases you gave is about AFL. Can ASAN-- support libfuzzer or other fuzzers to test large-scale software?
> > > > > 
> > > > > 
> > > > > Hi! This is a good question! Although we didn't test ASAN-- on libfuzzer, we believe you can apply ASAN-- on libfuzzer and other fuzzers, as long as you are using ASAN-- version Clang as compiler.
> > > > 
> > > > 
> > > > Is ASAN-- version Clang means clang-4.0？
> > > 
> > > 
> > > Yes, currently our stable version is Clang-4.0.0. We also migrated ASAN-- to LLVM-12.0.0, but it is preliminary version.
> > > I try to apply ASan--to the OSS-fuzz project and I have run the following commands：
> > > $ patch -p1 < patch_ASan--FuZZan
> > > $ cd llvm-4.0.0-project
> > > $ mkdir ASan--Build && cd ASan--Build
> > > $ cmake -DLLVM_ENABLE_PROJECTS="clang;compiler-rt" -G "Unix Makefiles" ../llvm
> > > $ make -j
> > > Since libfuzzer has been integrated into clang, should I use “/home/llvm-4.0.0-project/ASan--Build/bin/clang 251” or "Clang-4.0.0."  to compile the target softwares?
> 
> Hi, for ASan--, you need to use "/home/llvm-4.0.0-project/ASan--Build/bin/clang" to compile fuzzing targets.

Hello, it seems that the version of clang4.0 is too low for some projects. Can clang12 be used to establish ASan--?

**Comment by yzhang71** [comment]
> > > > > > > Hello, ASAN-- team! I noticed that the Fuzzing Test Cases you gave is about AFL. Can ASAN-- support libfuzzer or other fuzzers to test large-scale software?
> > > > > > 
> > > > > > 
> > > > > > Hi! This is a good question! Although we didn't test ASAN-- on libfuzzer, we believe you can apply ASAN-- on libfuzzer and other fuzzers, as long as you are using ASAN-- version Clang as compiler.
> > > > > 
> > > > > 
> > > > > Is ASAN-- version Clang means clang-4.0？
> > > > 
> > > > 
> > > > Yes, currently our stable version is Clang-4.0.0. We also migrated ASAN-- to LLVM-12.0.0, but it is preliminary version.
> > > > I try to apply ASan--to the OSS-fuzz project and I have run the following commands：
> > > > $ patch -p1 < patch_ASan--FuZZan
> > > > $ cd llvm-4.0.0-project
> > > > $ mkdir ASan--Build && cd ASan--Build
> > > > $ cmake -DLLVM_ENABLE_PROJECTS="clang;compiler-rt" -G "Unix Makefiles" ../llvm
> > > > $ make -j
> > > > Since libfuzzer has been integrated into clang, should I use “/home/llvm-4.0.0-project/ASan--Build/bin/clang 251” or "Clang-4.0.0."  to compile the target softwares?
> > 
> > 
> > Hi, for ASan--, you need to use "/home/llvm-4.0.0-project/ASan--Build/bin/clang" to compile fuzzing targets.
> 
> Hello, it seems that the version of clang4.0 is too low for some projects. Can clang12 be used to establish ASan--?

Yes, we also provided the clang-12.0.0 version of ASan--.

**Comment by dhbbb** [comment]
Are the procedure for compiling Asan-- with clang12 as following?&nbsp;
$ patch -p1 < patch_ASan--FuZZan
$ cd llvm-12.0.0-project
$ mkdir ASan--Build &amp;&amp; cd ASan--Build
$ cmake -DLLVM_ENABLE_PROJECTS="clang;compiler-rt" -G "Unix Makefiles" ../llvm
$ make -j



---Original---
From: "Yuchen ***@***.***&gt;
Date: Thu, Dec 9, 2021 23:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [junxzm1990/ASAN--] Questions about ASAN-- (Issue #1)




        
Hello, ASAN-- team! I noticed that the Fuzzing Test Cases you gave is about AFL. Can ASAN-- support libfuzzer or other fuzzers to test large-scale software?
  
Hi! This is a good question! Although we didn't test ASAN-- on libfuzzer, we believe you can apply ASAN-- on libfuzzer and other fuzzers, as long as you are using ASAN-- version Clang as compiler.
  
Is ASAN-- version Clang means clang-4.0？
  
Yes, currently our stable version is Clang-4.0.0. We also migrated ASAN-- to LLVM-12.0.0, but it is preliminary version.
 I try to apply ASan--to the OSS-fuzz project and I have run the following commands：
 $ patch -p1 < patch_ASan--FuZZan
 $ cd llvm-4.0.0-project
 $ mkdir ASan--Build &amp;&amp; cd ASan--Build
 $ cmake -DLLVM_ENABLE_PROJECTS="clang;compiler-rt" -G "Unix Makefiles" ../llvm
 $ make -j
 Since libfuzzer has been integrated into clang, should I use “/home/llvm-4.0.0-project/ASan--Build/bin/clang 251” or "Clang-4.0.0."  to compile the target softwares?
   
Hi, for ASan--, you need to use "/home/llvm-4.0.0-project/ASan--Build/bin/clang" to compile fuzzing targets.
  
Hello, it seems that the version of clang4.0 is too low for some projects. Can clang12 be used to establish ASan--?
  
Yes, we also provided the clang-12.0.0 version of ASan--.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yzhang71** [comment]
> Are the procedure for compiling Asan-- with clang12 as following?&nbsp; $ patch -p1 < patch_ASan--FuZZan $ cd llvm-12.0.0-project $ mkdir ASan--Build &amp;&amp; cd ASan--Build $ cmake -DLLVM_ENABLE_PROJECTS="clang;compiler-rt" -G "Unix Makefiles" ../llvm $ make -j
> […](#)
> ---Original--- From: "Yuchen ***@***.***&gt; Date: Thu, Dec 9, 2021 23:19 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [junxzm1990/ASAN--] Questions about ASAN-- (Issue #1) Hello, ASAN-- team! I noticed that the Fuzzing Test Cases you gave is about AFL. Can ASAN-- support libfuzzer or other fuzzers to test large-scale software? Hi! This is a good question! Although we didn't test ASAN-- on libfuzzer, we believe you can apply ASAN-- on libfuzzer and other fuzzers, as long as you are using ASAN-- version Clang as compiler. Is ASAN-- version Clang means clang-4.0？ Yes, currently our stable version is Clang-4.0.0. We also migrated ASAN-- to LLVM-12.0.0, but it is preliminary version. I try to apply ASan--to the OSS-fuzz project and I have run the following commands： $ patch -p1 < patch_ASan--FuZZan $ cd llvm-4.0.0-project $ mkdir ASan--Build &amp;&amp; cd ASan--Build $ cmake -DLLVM_ENABLE_PROJECTS="clang;compiler-rt" -G "Unix Makefiles" ../llvm $ make -j Since libfuzzer has been integrated into clang, should I use “/home/llvm-4.0.0-project/ASan--Build/bin/clang 251” or "Clang-4.0.0." to compile the target softwares? Hi, for ASan--, you need to use "/home/llvm-4.0.0-project/ASan--Build/bin/clang" to compile fuzzing targets. Hello, it seems that the version of clang4.0 is too low for some projects. Can clang12 be used to establish ASan--? Yes, we also provided the clang-12.0.0 version of ASan--. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Hi, for llvm 12, the patch is not applicable. If you want to fuzzing with llvm 12, you may need to migrate the patch manually, and the rest compilation steps are the same.

**Comment by blu3sh0rk** [comment]
> > Are the procedure for compiling Asan-- with clang12 as following?  $ patch -p1 < patch_ASan--FuZZan $ cd llvm-12.0.0-project $ mkdir ASan--Build && cd ASan--Build $ cmake -DLLVM_ENABLE_PROJECTS="clang;compiler-rt" -G "Unix Makefiles" ../llvm $ make -j
> > […](#)
> > ---Original--- From: "Yuchen _**@**_._**> Date: Thu, Dec 9, 2021 23:19 PM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [junxzm1990/ASAN--] Questions about ASAN-- (Issue #1) Hello, ASAN-- team! I noticed that the Fuzzing Test Cases you gave is about AFL. Can ASAN-- support libfuzzer or other fuzzers to test large-scale software? Hi! This is a good question! Although we didn't test ASAN-- on libfuzzer, we believe you can apply ASAN-- on libfuzzer and other fuzzers, as long as you are using ASAN-- version Clang as compiler. Is ASAN-- version Clang means clang-4.0？ Yes, currently our stable version is Clang-4.0.0. We also migrated ASAN-- to LLVM-12.0.0, but it is preliminary version. I try to apply ASan--to the OSS-fuzz project and I have run the following commands： $ patch -p1 < patch_ASan--FuZZan $ cd llvm-4.0.0-project $ mkdir ASan--Build && cd ASan--Build $ cmake -DLLVM_ENABLE_PROJECTS="clang;compiler-rt" -G "Unix Makefiles" ../llvm $ make -j Since libfuzzer has been integrated into clang, should I use “/home/llvm-4.0.0-project/ASan--Build/bin/clang 251” or "Clang-4.0.0." to compile the target softwares? Hi, for ASan--, you need to use "/home/llvm-4.0.0-project/ASan--Build/bin/clang" to compile fuzzing targets. Hello, it seems that the version of clang4.0 is too low for some projects. Can clang12 be used to establish ASan--? Yes, we also provided the clang-12.0.0 version of ASan--. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> 
> Hi, for llvm 12, the patch is not applicable. If you want to fuzzing with llvm 12, you may need to migrate the patch manually, and the rest compilation steps are the same.

Hello, do I just need to change llvm-4.0.0 in the patch file to llvm-12.0.0 or to make manual changes line by line?

**Comment by yzhang71** [comment]
> > > Are the procedure for compiling Asan-- with clang12 as following?  $ patch -p1 < patch_ASan--FuZZan $ cd llvm-12.0.0-project $ mkdir ASan--Build && cd ASan--Build $ cmake -DLLVM_ENABLE_PROJECTS="clang;compiler-rt" -G "Unix Makefiles" ../llvm $ make -j
> > > […](#)
> > > ---Original--- From: "Yuchen _**@**_._**> Date: Thu, Dec 9, 2021 23:19 PM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [junxzm1990/ASAN--] Questions about ASAN-- (Issue #1) Hello, ASAN-- team! I noticed that the Fuzzing Test Cases you gave is about AFL. Can ASAN-- support libfuzzer or other fuzzers to test large-scale software? Hi! This is a good question! Although we didn't test ASAN-- on libfuzzer, we believe you can apply ASAN-- on libfuzzer and other fuzzers, as long as you are using ASAN-- version Clang as compiler. Is ASAN-- version Clang means clang-4.0？ Yes, currently our stable version is Clang-4.0.0. We also migrated ASAN-- to LLVM-12.0.0, but it is preliminary version. I try to apply ASan--to the OSS-fuzz project and I have run the following commands： $ patch -p1 < patch_ASan--FuZZan $ cd llvm-4.0.0-project $ mkdir ASan--Build && cd ASan--Build $ cmake -DLLVM_ENABLE_PROJECTS="clang;compiler-rt" -G "Unix Makefiles" ../llvm $ make -j Since libfuzzer has been integrated into clang, should I use “/home/llvm-4.0.0-project/ASan--Build/bin/clang 251” or "Clang-4.0.0." to compile the target softwares? Hi, for ASan--, you need to use "/home/llvm-4.0.0-project/ASan--Build/bin/clang" to compile fuzzing targets. Hello, it seems that the version of clang4.0 is too low for some projects. Can clang12 be used to establish ASan--? Yes, we also provided the clang-12.0.0 version of ASan--. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> > 
> > 
> > Hi, for llvm 12, the patch is not applicable. If you want to fuzzing with llvm 12, you may need to migrate the patch manually, and the rest compilation steps are the same.
> 
> Hello, do I just need to change llvm-4.0.0 in the patch file to llvm-12.0.0 or to make manual changes line by line?

Hi, since the implementation of llvm-12.0.0 is a bit different from llvm-4.0.0, so I would recommend manually change llvm-12.0.0 according to the patch file.

**Comment by dhbbb** [comment]
> > > > Are the procedure for compiling Asan-- with clang12 as following?  $ patch -p1 < patch_ASan--FuZZan $ cd llvm-12.0.0-project $ mkdir ASan--Build && cd ASan--Build $ cmake -DLLVM_ENABLE_PROJECTS="clang;compiler-rt" -G "Unix Makefiles" ../llvm $ make -j
> > > > […](#)
> > > > ---Original--- From: "Yuchen _**@**_._**> Date: Thu, Dec 9, 2021 23:19 PM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [junxzm1990/ASAN--] Questions about ASAN-- (Issue #1) Hello, ASAN-- team! I noticed that the Fuzzing Test Cases you gave is about AFL. Can ASAN-- support libfuzzer or other fuzzers to test large-scale software? Hi! This is a good question! Although we didn't test ASAN-- on libfuzzer, we believe you can apply ASAN-- on libfuzzer and other fuzzers, as long as you are using ASAN-- version Clang as compiler. Is ASAN-- version Clang means clang-4.0？ Yes, currently our stable version is Clang-4.0.0. We also migrated ASAN-- to LLVM-12.0.0, but it is preliminary version. I try to apply ASan--to the OSS-fuzz project and I have run the following commands： $ patch -p1 < patch_ASan--FuZZan $ cd llvm-4.0.0-project $ mkdir ASan--Build && cd ASan--Build $ cmake -DLLVM_ENABLE_PROJECTS="clang;compiler-rt" -G "Unix Makefiles" ../llvm $ make -j Since libfuzzer has been integrated into clang, should I use “/home/llvm-4.0.0-project/ASan--Build/bin/clang 251” or "Clang-4.0.0." to compile the target softwares? Hi, for ASan--, you need to use "/home/llvm-4.0.0-project/ASan--Build/bin/clang" to compile fuzzing targets. Hello, it seems that the version of clang4.0 is too low for some projects. Can clang12 be used to establish ASan--? Yes, we also provided the clang-12.0.0 version of ASan--. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> > > 
> > > 
> > > Hi, for llvm 12, the patch is not applicable. If you want to fuzzing with llvm 12, you may need to migrate the patch manually, and the rest compilation steps are the same.
> > 
> > 
> > Hello, do I just need to change llvm-4.0.0 in the patch file to llvm-12.0.0 or to make manual changes line by line?
> 
> Hi, since the implementation of llvm-12.0.0 is a bit different from llvm-4.0.0, so I would recommend manually change llvm-12.0.0 according to the patch file.

Hello,i tried manually change llvm-12.0.0 according to the patch file,but It seems that there is a big difference between llvm12 and llvm4. For a person like me who don't know much about its implementation , it is difficult to patch manually.So can I use llvm12 to compile ASan-- source code without patching? Or do you plan to provide a patch for llvm12?

**Comment by yzhang71** [comment]
> 
Hi, yes you can compile ASan-- with llvm-12.0.0 without the patch. And yes, we may provide patch for llvm 12 in the future.

**Comment by yzhang71** [comment]
> > > > > Are the procedure for compiling Asan-- with clang12 as following?  $ patch -p1 < patch_ASan--FuZZan $ cd llvm-12.0.0-project $ mkdir ASan--Build && cd ASan--Build $ cmake -DLLVM_ENABLE_PROJECTS="clang;compiler-rt" -G "Unix Makefiles" ../llvm $ make -j
> > > > > […](#)
> > > > > ---Original--- From: "Yuchen _**@**_._**> Date: Thu, Dec 9, 2021 23:19 PM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [junxzm1990/ASAN--] Questions about ASAN-- (Issue #1) Hello, ASAN-- team! I noticed that the Fuzzing Test Cases you gave is about AFL. Can ASAN-- support libfuzzer or other fuzzers to test large-scale software? Hi! This is a good question! Although we didn't test ASAN-- on libfuzzer, we believe you can apply ASAN-- on libfuzzer and other fuzzers, as long as you are using ASAN-- version Clang as compiler. Is ASAN-- version Clang means clang-4.0？ Yes, currently our stable version is Clang-4.0.0. We also migrated ASAN-- to LLVM-12.0.0, but it is preliminary version. I try to apply ASan--to the OSS-fuzz project and I have run the following commands： $ patch -p1 < patch_ASan--FuZZan $ cd llvm-4.0.0-project $ mkdir ASan--Build && cd ASan--Build $ cmake -DLLVM_ENABLE_PROJECTS="clang;compiler-rt" -G "Unix Makefiles" ../llvm $ make -j Since libfuzzer has been integrated into clang, should I use “/home/llvm-4.0.0-project/ASan--Build/bin/clang 251” or "Clang-4.0.0." to compile the target softwares? Hi, for ASan--, you need to use "/home/llvm-4.0.0-project/ASan--Build/bin/clang" to compile fuzzing targets. Hello, it seems that the version of clang4.0 is too low for some projects. Can clang12 be used to establish ASan--? Yes, we also provided the clang-12.0.0 version of ASan--. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> > > > 
> > > > 
> > > > Hi, for llvm 12, the patch is not applicable. If you want to fuzzing with llvm 12, you may need to migrate the patch manually, and the rest compilation steps are the same.
> > > 
> > > 
> > > Hello, do I just need to change llvm-4.0.0 in the patch file to llvm-12.0.0 or to make manual changes line by line?
> > 
> > 
> > Hi, since the implementation of llvm-12.0.0 is a bit different from llvm-4.0.0, so I would recommend manually change llvm-12.0.0 according to the patch file.
> 
> Hello,i tried manually change llvm-12.0.0 according to the patch file,but It seems that there is a big difference between llvm12 and llvm4. For a person like me who don't know much about its implementation , it is difficult to patch manually.So can I use llvm12 to compile ASan-- source code without patching? Or do you plan to provide a patch for llvm12?

Hi, yes you can compile ASan-- with llvm-12.0.0 without the patch. And yes, we may provide patch for llvm 12 in the future.

**Comment by dhbbb** [comment]
> > > > > > Are the procedure for compiling Asan-- with clang12 as following?  $ patch -p1 < patch_ASan--FuZZan $ cd llvm-12.0.0-project $ mkdir ASan--Build && cd ASan--Build $ cmake -DLLVM_ENABLE_PROJECTS="clang;compiler-rt" -G "Unix Makefiles" ../llvm $ make -j
> > > > > > […](#)
> > > > > > ---Original--- From: "Yuchen _**@**_._**> Date: Thu, Dec 9, 2021 23:19 PM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [junxzm1990/ASAN--] Questions about ASAN-- (Issue #1) Hello, ASAN-- team! I noticed that the Fuzzing Test Cases you gave is about AFL. Can ASAN-- support libfuzzer or other fuzzers to test large-scale software? Hi! This is a good question! Although we didn't test ASAN-- on libfuzzer, we believe you can apply ASAN-- on libfuzzer and other fuzzers, as long as you are using ASAN-- version Clang as compiler. Is ASAN-- version Clang means clang-4.0？ Yes, currently our stable version is Clang-4.0.0. We also migrated ASAN-- to LLVM-12.0.0, but it is preliminary version. I try to apply ASan--to the OSS-fuzz project and I have run the following commands： $ patch -p1 < patch_ASan--FuZZan $ cd llvm-4.0.0-project $ mkdir ASan--Build && cd ASan--Build $ cmake -DLLVM_ENABLE_PROJECTS="clang;compiler-rt" -G "Unix Makefiles" ../llvm $ make -j Since libfuzzer has been integrated into clang, should I use “/home/llvm-4.0.0-project/ASan--Build/bin/clang 251” or "Clang-4.0.0." to compile the target softwares? Hi, for ASan--, you need to use "/home/llvm-4.0.0-project/ASan--Build/bin/clang" to compile fuzzing targets. Hello, it seems that the version of clang4.0 is too low for some projects. Can clang12 be used to establish ASan--? Yes, we also provided the clang-12.0.0 version of ASan--. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> > > > > 
> > > > > 
> > > > > Hi, for llvm 12, the patch is not applicable. If you want to fuzzing with llvm 12, you may need to migrate the patch manually, and the rest compilation steps are the same.
> > > > 
> > > > 
> > > > Hello, do I just need to change llvm-4.0.0 in the patch file to llvm-12.0.0 or to make manual changes line by line?
> > > 
> > > 
> > > Hi, since the implementation of llvm-12.0.0 is a bit different from llvm-4.0.0, so I would recommend manually change llvm-12.0.0 according to the patch file.
> > 
> > 
> > Hello,i tried manually change llvm-12.0.0 according to the patch file,but It seems that there is a big difference between llvm12 and llvm4. For a person like me who don't know much about its implementation , it is difficult to patch manually.So can I use llvm12 to compile ASan-- source code without patching? Or do you plan to provide a patch for llvm12?
> 
> Hi, yes you can compile ASan-- with llvm-12.0.0 without the patch. And yes, we may provide patch for llvm 12 in the future.

Thanks for you quick reply!Since I don't quite understand the role of patch,will compile ASan-- with llvm-12.0.0 without the patch affect the effect of fuzzing？

**Comment by yzhang71** [comment]
> > > > > > > Are the procedure for compiling Asan-- with clang12 as following?  $ patch -p1 < patch_ASan--FuZZan $ cd llvm-12.0.0-project $ mkdir ASan--Build && cd ASan--Build $ cmake -DLLVM_ENABLE_PROJECTS="clang;compiler-rt" -G "Unix Makefiles" ../llvm $ make -j
> > > > > > > […](#)
> > > > > > > ---Original--- From: "Yuchen _**@**_._**> Date: Thu, Dec 9, 2021 23:19 PM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [junxzm1990/ASAN--] Questions about ASAN-- (Issue #1) Hello, ASAN-- team! I noticed that the Fuzzing Test Cases you gave is about AFL. Can ASAN-- support libfuzzer or other fuzzers to test large-scale software? Hi! This is a good question! Although we didn't test ASAN-- on libfuzzer, we believe you can apply ASAN-- on libfuzzer and other fuzzers, as long as you are using ASAN-- version Clang as compiler. Is ASAN-- version Clang means clang-4.0？ Yes, currently our stable version is Clang-4.0.0. We also migrated ASAN-- to LLVM-12.0.0, but it is preliminary version. I try to apply ASan--to the OSS-fuzz project and I have run the following commands： $ patch -p1 < patch_ASan--FuZZan $ cd llvm-4.0.0-project $ mkdir ASan--Build && cd ASan--Build $ cmake -DLLVM_ENABLE_PROJECTS="clang;compiler-rt" -G "Unix Makefiles" ../llvm $ make -j Since libfuzzer has been integrated into clang, should I use “/home/llvm-4.0.0-project/ASan--Build/bin/clang 251” or "Clang-4.0.0." to compile the target softwares? Hi, for ASan--, you need to use "/home/llvm-4.0.0-project/ASan--Build/bin/clang" to compile fuzzing targets. Hello, it seems that the version of clang4.0 is too low for some projects. Can clang12 be used to establish ASan--? Yes, we also provided the clang-12.0.0 version of ASan--. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> > > > > > 
> > > > > > 
> > > > > > Hi, for llvm 12, the patch is not applicable. If you want to fuzzing with llvm 12, you may need to migrate the patch manually, and the rest compilation steps are the same.
> > > > > 
> > > > > 
> > > > > Hello, do I just need to change llvm-4.0.0 in the patch file to llvm-12.0.0 or to make manual changes line by line?
> > > > 
> > > > 
> > > > Hi, since the implementation of llvm-12.0.0 is a bit different from llvm-4.0.0, so I would recommend manually change llvm-12.0.0 according to the patch file.
> > > 
> > > 
> > > Hello,i tried manually change llvm-12.0.0 according to the patch file,but It seems that there is a big difference between llvm12 and llvm4. For a person like me who don't know much about its implementation , it is difficult to patch manually.So can I use llvm12 to compile ASan-- source code without patching? Or do you plan to provide a patch for llvm12?
> > 
> > 
> > Hi, yes you can compile ASan-- with llvm-12.0.0 without the patch. And yes, we may provide patch for llvm 12 in the future.
> 
> Thanks for you quick reply!Since I don't quite understand the role of patch,will compile ASan-- with llvm-12.0.0 without the patch affect the effect of fuzzing？

Yes, the patch is disabling the logging functionality of ASan. Without the patching, fuzzing can still benefit from removing redundant checks, but may less effect as patched version.
