### ISSUE TITLE
AddressSanitizer Pass used in overhead test

### ISSUE THREAD

**Issue by MJUCOM** [junxzm1990/ASAN--#3]
Hello!

I read the 'Debloating address sanitizer 'paper too well. It was a very good, interesting and intriguing thesis. I am studying address sanitizer, and in the process of studying address sanitizer.

In the motivating study part of the paper, it was confirmed that the function of address sanitizer was divided into a total of 7 and analyzed how much overhead occurred for each. It means that the test about ASan, Sanitizer_Chk, interceptors, Poisoning, Logging, Heap Management, RedZone.

If you don't mind, I wonder if you could provide the addresssanitizer pass used in each test environment as an open source. This is the source code that disables the code for AddressSanitizer.cpp belonging to llvm according to each environment.

I wanted to send you an email, but I couldn't check your email, so I write the git issue.

Could you please share the code for the addresssanitizer pass you used in the test?

Thank you!
Have a nice day!

**Comment by yzhang71** [comment]
Hi,

Please send e-mail to yzhang0701@gmail.com, and I can help you from there.

Best,

Yuchen Zhang
